// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlSSCDk40C-oTNvGaboiXp7pk9PHHewVU',
    appId: '1:382315173639:web:d02e47370147a61ab2d7a2',
    messagingSenderId: '382315173639',
    projectId: 'urbanhero-23968',
    authDomain: 'urbanhero-23968.firebaseapp.com',
    storageBucket: 'urbanhero-23968.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQfY3DMMam3nuwZvDVEMmscNhrgxZOh10',
    appId: '1:382315173639:android:b1f7969a056c99e3b2d7a2',
    messagingSenderId: '382315173639',
    projectId: 'urbanhero-23968',
    storageBucket: 'urbanhero-23968.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsshlMsfXEbWf_jMB2txTZZtP1gUEaYks',
    appId: '1:382315173639:ios:8d8091a4fbeca4e6b2d7a2',
    messagingSenderId: '382315173639',
    projectId: 'urbanhero-23968',
    storageBucket: 'urbanhero-23968.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsshlMsfXEbWf_jMB2txTZZtP1gUEaYks',
    appId: '1:382315173639:ios:8d8091a4fbeca4e6b2d7a2',
    messagingSenderId: '382315173639',
    projectId: 'urbanhero-23968',
    storageBucket: 'urbanhero-23968.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlSSCDk40C-oTNvGaboiXp7pk9PHHewVU',
    appId: '1:382315173639:web:4b788de9d09df272b2d7a2',
    messagingSenderId: '382315173639',
    projectId: 'urbanhero-23968',
    authDomain: 'urbanhero-23968.firebaseapp.com',
    storageBucket: 'urbanhero-23968.firebasestorage.app',
  );
}
