// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSBbazvpbS_M7UgRA6BoheG_vwPnmUKHY',
    appId: '1:727147786914:web:c432ecc6fe23650dcbddfb',
    messagingSenderId: '727147786914',
    projectId: 'urban-hero-d267f',
    authDomain: 'urban-hero-d267f.firebaseapp.com',
    storageBucket: 'urban-hero-d267f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB3j5oPL92yXy0_f5T25q3q11vZ4CCL3o',
    appId: '1:727147786914:android:aaec7b6fe961e543cbddfb',
    messagingSenderId: '727147786914',
    projectId: 'urban-hero-d267f',
    storageBucket: 'urban-hero-d267f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8UjImwS-bHuaN3ett8RlgXYKqfiMUT24',
    appId: '1:727147786914:ios:1c5d84a7fa7c52d0cbddfb',
    messagingSenderId: '727147786914',
    projectId: 'urban-hero-d267f',
    storageBucket: 'urban-hero-d267f.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8UjImwS-bHuaN3ett8RlgXYKqfiMUT24',
    appId: '1:727147786914:ios:1c5d84a7fa7c52d0cbddfb',
    messagingSenderId: '727147786914',
    projectId: 'urban-hero-d267f',
    storageBucket: 'urban-hero-d267f.firebasestorage.app',
    iosBundleId: 'com.example.guardian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSBbazvpbS_M7UgRA6BoheG_vwPnmUKHY',
    appId: '1:727147786914:web:00a7e575f4217555cbddfb',
    messagingSenderId: '727147786914',
    projectId: 'urban-hero-d267f',
    authDomain: 'urban-hero-d267f.firebaseapp.com',
    storageBucket: 'urban-hero-d267f.firebasestorage.app',
  );
}
